# Automatically generated stub file; Generated by 'surface' (pip install surface).
# Module: docstring

import typing

class InitDoc(object):
    """
        Typing information in docstring
        Args:
            name (str)
    """

    def __init__(self, name: str) -> None:
        ""
