# Automatically generated stub file; Generated by 'surface' (pip install surface).
# Module: simple

import typing

class SimpleClass(object):
    ""

    @classmethod
    def simple_class_method(cls, name: typing.Any) -> typing.Any:
        """
            A simple class method!
        """

    def simple_method(self, name: typing.Any) -> typing.Any:
        """
            A simple method!
        """

def simple_function(name: typing.Any) -> typing.Any:
    ""
